export const baseEquipment = [
  {
    id: "E1",
    name: "E1",
    display: "Eastman 1",
    cell: "CNC Machines",
    pmPriority: 2.0,
    safety: 2,
    maint: 2,
    pmOverdue: 2,
    pmUpcoming: 3,
    details: {
      description: "Eastman Cutting Machine",
      productionArea: "Sub Assembly",
      workStation: "Eastman 1",
      category: "CNC Cutting Machine",
      trackRunTime: "Yes (Hours)",
      notes: "This is the older cutting machine",
      serial: "1234abc",
      manufacturer: "Eastman Cutting",
      model: "C123",
      servicePhone: "(555) 555-5555",
    },
  },
  {
    id: "E2",
    name: "E2",
    display: "Sewing 1",
    cell: "Welders",
    pmPriority: 1.5,
    safety: 1,
    maint: 1,
    pmOverdue: 1,
    pmUpcoming: 2,
    details: {
      description: "Industrial Sewing Machine",
      productionArea: "Assembly",
      workStation: "Sewing 1",
      category: "Sewers",
      trackRunTime: "No",
      notes: "New belt fitted last month",
      serial: "S-2045",
      manufacturer: "SewAll",
      model: "SX-1",
      servicePhone: "(555) 111-2222",
    },
  },
  {
    id: "E3",
    name: "E3",
    display: "PH5800",
    cell: "Welders",
    pmPriority: 0.95,
    safety: 0,
    maint: 2,
    pmOverdue: 0,
    pmUpcoming: 3,
    details: {
      description: "Precision Head 5800",
      productionArea: "Assembly",
      workStation: "PH5800",
      category: "Heads",
      trackRunTime: "Yes (Hours)",
      notes: "Requires calibration quarterly",
      serial: "PH-5800-99",
      manufacturer: "Precise",
      model: "PH-5800",
      servicePhone: "(555) 777-8888",
    },
  },
  {
    id: "E4",
    name: "E4",
    display: "Welder 1",
    cell: "Printers",
    pmPriority: 0.7,
    safety: 0,
    maint: 0,
    pmOverdue: 0,
    pmUpcoming: 0,
    details: {
      description: "Arc Welder Station 1",
      productionArea: "Welding",
      workStation: "Welder 1",
      category: "Welders",
      trackRunTime: "No",
      notes: "Stable",
      serial: "WLD-1",
      manufacturer: "SparkCo",
      model: "ARC-1",
      servicePhone: "(555) 222-3333",
    },
  },
  {
    id: "E5",
    name: "E5",
    display: "Welder 3",
    cell: "CNC Machines",
    pmPriority: 0.6,
    safety: 0,
    maint: 0,
    pmOverdue: 0,
    pmUpcoming: 0,
    details: {
      description: "Arc Welder Station 3",
      productionArea: "Welding",
      workStation: "Welder 3",
      category: "Welders",
      trackRunTime: "No",
      notes: "Baseline unit",
      serial: "WLD-3",
      manufacturer: "SparkCo",
      model: "ARC-3",
      servicePhone: "(555) 222-9999",
    },
  },
];

export function getEquipmentList() {
  const list = [];
  for (let i = 0; i < 15; i++) {
    const b = baseEquipment[i % baseEquipment.length];
    list.push({
      ...b,
      id: `E${i + 1}`,
      name: `E${i + 1}`,
      display: i < baseEquipment.length ? b.display : `${b.display} (${i + 1})`,
    });
  }
  return list;
}